name: Format check

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  ruff-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Check formatting
        run: uvx ruff format --check .

      - name: Check linting
        run: uvx ruff check .

      - name: Check types
        run: uv run mypy pycoin
