name: Tests and coverage

on:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        python-version: [2.7]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Python 2.7
      run: |
        sudo apt-get update
        sudo apt-get install -y software-properties-common
        sudo add-apt-repository universe
        sudo apt-get install -y python2
        python2 --version

    - name: Install pip for Python 2.7
      run: |
        curl https://bootstrap.pypa.io/pip/2.7/get-pip.py -o get-pip.py
        sudo python2 get-pip.py
        python2 -m pip --version

    - name: Test core code with pytest
      run: |
        pip install coverage pytest
        coverage run -m pytest tests
